"""
Extended Event type with industrial safety standards.

This module provides a backward-compatible Event class with:
- risk_level (1-9) instead of urgency (0-1)
- event_name for categorical event types
- Full compatibility with existing code via urgency property
"""

from dataclasses import dataclass
from typing import Tuple, Optional


@dataclass(frozen=True)
class Event:
    """
    Represents a detected event from the CCTV system.

    Events are generated by CCTV monitoring and may require robot investigation.
    Each event has spatial location, temporal information, and risk assessment
    following industrial safety evaluation standards (Korean KOSHA/MOEL guidelines).

    Attributes:
        x: X-coordinate in meters (map frame)
        y: Y-coordinate in meters (map frame)
        risk_level: Risk level (1-9, following industrial safety standards)
                   1-3: Low risk (minor incidents, routine check)
                   4-6: Medium risk (investigation required, potential hazards)
                   7-9: High risk (immediate response, critical safety events)
        event_name: Type of event (e.g., "화재감지", "무단침입", "낙하물감지")
        confidence: Detection confidence (0.0-1.0, from CCTV classifier)
        detection_time: When event was first detected (seconds since episode start)
        event_id: Unique identifier for this event
        is_active: Whether this event is still unresolved

    Note:
        Risk levels follow industrial safety evaluation standards (산업안전보건법):
        - Level 1-3: 저위험 (Low risk) - monitoring, routine check
        - Level 4-6: 중위험 (Medium risk) - investigation required
        - Level 7-9: 고위험 (High risk) - immediate response critical

        Confidence reflects the CCTV classifier's certainty (0.0-1.0).

        For backward compatibility, the 'urgency' property is provided:
        urgency = risk_level / 9.0  (converts 1-9 to 0.11-1.0 scale)

    Example:
        >>> event = Event(
        ...     x=20.0, y=15.0,
        ...     risk_level=8,
        ...     event_name="화재감지",
        ...     confidence=0.95,
        ...     detection_time=100.0,
        ...     event_id=1
        ... )
        >>> if event.risk_level >= 7 and event.confidence > 0.9:
        ...     print("Critical safety event requiring immediate response")
        >>> print(f"Legacy urgency score: {event.urgency:.2f}")  # 0.89
    """
    x: float
    y: float
    risk_level: int  # 1-9 (industrial safety standard)
    event_name: str  # Event type name
    confidence: float  # 0.0-1.0
    detection_time: float
    event_id: int
    is_active: bool = True

    @property
    def urgency(self) -> float:
        """
        Legacy urgency score (0.0-1.0) for backward compatibility.

        Computed from risk_level: urgency = risk_level / 9.0
        This maps 1-9 risk levels to approximately 0.11-1.0 range.

        Returns:
            urgency: Float in [0.11, 1.0] representing urgency
        """
        return self.risk_level / 9.0

    @property
    def position(self) -> Tuple[float, float]:
        """Returns the (x, y) position as a tuple."""
        return (self.x, self.y)

    def time_elapsed(self, current_time: float) -> float:
        """
        Calculate time elapsed since event detection.

        Args:
            current_time: Current episode time in seconds

        Returns:
            Time elapsed in seconds
        """
        return current_time - self.detection_time

    @property
    def is_critical(self) -> bool:
        """Check if event is critical (risk level >= 7)."""
        return self.risk_level >= 7

    @property
    def is_high_confidence(self) -> bool:
        """Check if detection confidence is high (>= 0.8)."""
        return self.confidence >= 0.8

    @property
    def requires_immediate_response(self) -> bool:
        """Check if event requires immediate response (critical + high confidence)."""
        return self.is_critical and self.is_high_confidence

    @classmethod
    def from_legacy(
        cls,
        x: float,
        y: float,
        urgency: float,
        confidence: float,
        detection_time: float,
        event_id: int,
        event_name: Optional[str] = None,
        is_active: bool = True
    ) -> 'Event':
        """
        Create Event from legacy urgency-based format.

        Converts urgency (0.0-1.0) to risk_level (1-9).

        Args:
            urgency: Legacy urgency score (0.0-1.0)
            event_name: If None, defaults to "이벤트" + risk level

        Returns:
            Event instance with converted risk_level
        """
        # Convert urgency (0-1) to risk_level (1-9)
        risk_level = max(1, min(9, int(urgency * 9) + 1))

        if event_name is None:
            # Default event name based on urgency
            if risk_level >= 7:
                event_name = "고위험이벤트"
            elif risk_level >= 4:
                event_name = "중위험이벤트"
            else:
                event_name = "저위험이벤트"

        return cls(
            x=x,
            y=y,
            risk_level=risk_level,
            event_name=event_name,
            confidence=confidence,
            detection_time=detection_time,
            event_id=event_id,
            is_active=is_active
        )


# For validation
def validate_event(event: Event) -> None:
    """
    Validate event attributes.

    Args:
        event: Event to validate

    Raises:
        ValueError: If any attribute is invalid
    """
    if not (1 <= event.risk_level <= 9):
        raise ValueError(f"risk_level must be 1-9, got {event.risk_level}")
    if not (0.0 <= event.confidence <= 1.0):
        raise ValueError(f"confidence must be 0.0-1.0, got {event.confidence}")
    if event.detection_time < 0:
        raise ValueError(f"detection_time must be >= 0, got {event.detection_time}")
    if not event.event_name:
        raise ValueError("event_name cannot be empty")
